apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: username.jar
        required: true

jobs:
  build:
    steps:
      - name: Upload to Nexus
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          curl -u ${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}} --upload-file ${{inputs.pathtobinary}} ${{vars.nexus_training_actions_url}}
