apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Get artifact digest
        id: step6
        uses: docker://ganeshpl/alpine-jq
        shell: sh
        run: |
          echo "a0123456789a" > "$CLOUDBEES_OUTPUTS/digest"
      - name: Register built artifact
        id: step7
        uses: cloudbees-io/register-build-artifact@v1
        with:
          version: "version"
          url: "url"
          digest: ${{steps.step6.outputs.digest}} 
          name: "name"