apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: example.txt
        required: true

jobs:
  build:
    steps:
      - name: Create file
        uses: docker://curlimages/curl:latest
        shell: sh
        run: echo "This is an example file - $(date)" > ${{inputs.pathtobinary}}
      - name: Upload to Nexus
        uses: docker://curlimages/curl:latest
        shell: sh
        run: |
          curl -u ${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}} \
              --upload-file ${{inputs.pathtobinary}} \
              -H "Content-Disposition: attachment; filename=${{inputs.pathtobinary}}" \
              ${{vars.nexus_training_actions_url}}
      - name: List artifacts in repo
        uses: docker://curlimages/curl:latest
        shell: sh
        run:  |
          curl -s -u ${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}} \
             "http://https://nexus.cloudbees.guru:8081//service/rest/v1/search?repository=unify-docker-training" \
             | jq -r '.items[].assets[].downloadUrl'
