apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 3 A
on:
  workflow_dispatch:
jobs:
  use-action:
    steps:
      - name: Create Upload and Register binary
        uses: mluzcabrera/actiontraining@main
        with:
          string-val: 'test string'
