apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: example.txt
        required: true
jobs:
  build:
    steps:
      - name: Get artifact digest
        id: step6
        uses: docker://ganeshpl/alpine-jq
        shell: sh
        run: |
          echo "$(curl -s -u '${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}}' 'https://nexus.cloudbees.guru:8081/service/rest/v1/assets?repository=unify-docker-training' | jq -r '.items[] | select(.path == "example.txt") | .checksum.md5' )" > "$CLOUDBEES_OUTPUTS/caca"
      - name: print
        uses: docker://alpine:3.18
        id: step2
        run: echo ${{ steps.step6.outputs.caca }}
