apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: example.txt
        required: true
      artifactversion:
        type: string
        default: 1.0.0
        required: true
jobs:
  build:
    steps:
      - name: Get artifact digest
        id: step6
        uses: docker://ganeshpl/alpine-jq
        shell: sh
        run: |
          echo $(curl -s -u '${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}}' 'https://nexus.cloudbees.guru:8081/service/rest/v1/assets?repository=unify-docker-training' | jq -r '.items[] | select(.path == "${{inputs.pathtobinary}}") | .checksum.md5' )
      - name: Register built artifact
        id: step7
        uses: cloudbees-io/register-build-artifact@v1
        with:
          version: ${{inputs.artifactversion}}
          url: ${{vars.nexus_training_actions_repo}}${{inputs.pathtobinary}}
          digest: $(curl -s -u '${{vars.nexus_training_actions_user}}:${{secrets.nexus_training_actions_secret}}' 'https://nexus.cloudbees.guru:8081/service/rest/v1/assets?repository=unify-docker-training' | jq -r '.items[] | select(.path == "${{inputs.pathtobinary}}") | .checksum.md5' )
          name: ${{inputs.pathtobinary}}

