apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Exercise 2 A
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: username.jar
        required: true

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          curl -u ${{vars.username}}:${{secrets.password}} --upload-file ${{inputs.pathtobinary}} ${{vars.repo}}
